#Requires -Version 5.1
<#
.SYNOPSIS
    Regenerates docs/CONTROL-MAPPING.md from the registered checks and remediations.
.PARAMETER IncludePacks
    Also document checks and remediations from installed packs. Off by default so
    a locally installed (possibly paid) pack never ends up in the repository docs.
#>
[CmdletBinding()]
param([string]$Path, [switch]$IncludePacks)

$root = Split-Path -Parent $PSScriptRoot
if (-not $Path) { $Path = Join-Path (Join-Path $root 'docs') 'CONTROL-MAPPING.md' }
Import-Module (Join-Path (Join-Path (Join-Path $root 'src') 'CEAudit') 'CEAudit.psd1') -Force

$builtIn = [ordered]@{
    Firewalls                = 'Firewalls'
    SecureConfiguration      = 'Secure configuration'
    SecurityUpdateManagement = 'Security update management'
    UserAccessControl        = 'User access control'
    MalwareProtection        = 'Malware protection'
    NCSCHardening            = 'NCSC device guidance (beyond Cyber Essentials)'
}
# Built-in categories use their document headings; categories from installed packs follow.
$packRemediations = @(Get-CEPack | ForEach-Object { $_.Remediations })
$checks = @(Get-CECheck | Where-Object { $IncludePacks -or -not $_.Pack })
$remediations = @(Get-CERemediation | Where-Object { $IncludePacks -or $packRemediations -notcontains $_.Id })
$labels = [ordered]@{}
$n = 0
foreach ($category in @(Get-CECategory | Where-Object { $IncludePacks -or -not $_.Pack })) {
    $n++
    $label = if ($builtIn.Contains($category.Id)) { $builtIn[$category.Id] } else { "$($category.Label) (pack: $($category.Pack))" }
    $labels[$category.Id] = "$n. $label"
}

$lines = New-Object System.Collections.ArrayList
[void]$lines.Add('# Control mapping')
[void]$lines.Add('')
[void]$lines.Add('Generated by `tools/Export-ControlMapping.ps1`. Do not edit by hand.')
[void]$lines.Add('')
[void]$lines.Add('Sources:')
[void]$lines.Add('')
[void]$lines.Add('- NCSC, *Cyber Essentials: Requirements for IT Infrastructure* v3.3 ("Danzell"), in force from April 2026')
[void]$lines.Add('- IASME/NCSC, *Cyber Essentials Plus test specification* (TC1 to TC5)')
[void]$lines.Add('- NCSC, *Device security guidance: Windows*')
[void]$lines.Add('')
[void]$lines.Add('**Auto-fail** marks the v3.3 questions that fail an assessment outright: MFA on cloud services, and OS/firmware (A6.4) and application (A6.5) updates within 14 days. SU-01 is also flagged because an unsupported OS cannot receive those updates.')
[void]$lines.Add('')
[void]$lines.Add("$($checks.Count) checks, $($remediations.Count) automated remediations.")

foreach ($cat in $labels.Keys) {
    [void]$lines.Add('')
    [void]$lines.Add("## $($labels[$cat])")
    [void]$lines.Add('')
    [void]$lines.Add('| ID | Check | Severity | Auto-fail | Admin | Frameworks | Requirement |')
    [void]$lines.Add('|---|---|---|:-:|:-:|---|---|')
    foreach ($c in ($checks | Where-Object { $_.Category -eq $cat } | Sort-Object Id)) {
        $af = if ($c.AutoFail) { 'Yes' } else { '' }
        $ad = if ($c.RequiresAdmin) { 'Yes' } else { '' }
        [void]$lines.Add("| $($c.Id) | $($c.Title) | $($c.Severity) | $af | $ad | $($c.Frameworks -join ', ') | $($c.Reference -replace '\|', '/') |")
    }
}

[void]$lines.Add('')
[void]$lines.Add('## Remediation library')
[void]$lines.Add('')
[void]$lines.Add('Changesets can only reference these. **Default** = ticked in a new changeset (High risk is never ticked by default).')
[void]$lines.Add('')
[void]$lines.Add('| Remediation | What it does | Risk | Default | Admin | Restart | Reversible | Notes |')
[void]$lines.Add('|---|---|---|:-:|:-:|:-:|:-:|---|')
foreach ($r in $remediations) {
    $yn = { param($b) if ($b) { 'Yes' } else { '' } }
    [void]$lines.Add("| ``$($r.Id)`` | $($r.Title) | $($r.Risk) | $(& $yn $r.SelectedByDefault) | $(& $yn $r.RequiresAdmin) | $(& $yn $r.RequiresReboot) | $(& $yn $r.Reversible) | $($r.Notes) |")
}

$lines -join "`n" | Set-Content -LiteralPath $Path -Encoding UTF8
Write-Host "Wrote $Path"
